### ISSUE TITLE
Compatibility with Irrlicht Lime

### ISSUE THREAD

**Issue by barefists** [skylicht-lab/skylicht-engine#115]
How compatible is the API compared to the original Irrlicht? Will it be possible to use Skylicht as a drop-in replacement for Irrlicht in [Irrlicht Lime](https://github.com/greenya/irrlichtlime)?

**Comment by ducphamhong** [comment]
On Skylicht Roadmap, I drop SceneManager, scene nodes struct and replace by the Entity component system (ECS).
I just use at core system VideoDriver, Image, FileSystem, MeshBuffer from Irrlicht.

**Comment by barefists** [comment]
I see, thanks for the clarification.
