### ISSUE TITLE
Is this engine ready for production?

### ISSUE THREAD

**Issue by cpusam** [skylicht-lab/skylicht-engine#124]
So, can I use this engine for make some game, or is ready for production?

**Comment by ducphamhong** [comment]
Skylicht LTD used this to made own game. But we are owner of this project, so we can handle this.
You can use to make your game. But it still have some risky when project still in progress.
I hope when the editor is complete, it is ready for production. Plan is end of this year.
Thanks

**Comment by ducphamhong** [comment]
The next plan:
- I will implement Metal Driver for IOS/MAC instead use Angle from Google.
- Android Project for apk, obb... build
- The editor for easy build scene

**Comment by cpusam** [comment]
@ducphamhong So, I will wait for the end dev of editor. Thanks.
