### ISSUE TITLE
How about little bit smooth shadows with simple pseudo noise function in shaders? 

### ISSUE THREAD

**Issue by savegame** [skylicht-lab/skylicht-engine#130]
Default shadow
![default_shadows](https://user-images.githubusercontent.com/16311332/134118339-21ef574a-86f9-4b94-9717-e869ab20f1c9.png)  

```
vec2 rand(vec2 co){
    return vec2(fract(sin(dot(co.xy ,vec2(12.9898,78.233))) * 43758.5453),
	fract(sin(dot(co.yx ,vec2(12.9898,78.233))) * 43758.5453)) * 0.00047;
}
```  

single step Noised shadow
![noised_shadows](https://user-images.githubusercontent.com/16311332/134118362-e982ac55-0283-4ee3-b8b3-8c419d89eb1b.png)
```
// before for loop 
vec2 rnd_noise = rand(uv);
// then in for loop 
result += texture2DCompare(vec3(uv + off + rnd_noise, id), depth - bias);
```  

Noise in For loop in shadow function (more smooth)  
![more_noised_shadows](https://user-images.githubusercontent.com/16311332/134119366-5bcfb9e3-cac8-4147-b7bc-77d16ced0442.png)    
```
// and use it in for loop in shadow function for uv + offset 
result += texture2DCompare(vec3(uv + off + rand(uv + off), id), depth - bias);
```  

if you like it, i'll create MR/PR to your master branch. :) 

P.S. a good continuation of the irrlicht engine! :+1:

**Comment by ducphamhong** [comment]
Hi, thank you. i will update it
