### ISSUE TITLE
Is there any plan to support Blend-Shapes (Morph animation) in the near future?

### ISSUE THREAD

**Issue by babefish2008** [skylicht-lab/skylicht-engine#135]
Hi Hung, 

Firstly, Really appreciate to contribute Skylicht-Engine, this engine is very helpful for my app! I have a look at the feature list and it seems skylicht did't find Blend-shapes(Morph animation) support, right? Do you have plan to support this feature?

**Comment by ducphamhong** [comment]
Hi bebefinish
Thanks for your request.

I have the question:  The meshes, that will be blending are the same as the number of vertices?
I will open issues to R&D soon this feature.

Thanks,

**Comment by ducphamhong** [comment]
I have an example here. I going to write the fbx importer and merge this feature.

https://github.com/bqqbarbhg/ufbx/blob/master/examples/viewer/shaders/mesh.glsl

Thanks your advice

**Comment by ducphamhong** [comment]
Hi @babefish2008 
I have added the project **Blend Shapes** example here:
https://github.com/skylicht-lab/skylicht-engine/tree/master/Samples/BlendShape/Source
