### ISSUE TITLE
Does skylicht only supports glsl 4.0 ?

### ISSUE THREAD

**Issue by Joilnen** [skylicht-lab/skylicht-engine#142]
When I try to run in linux with intel gpu I got this, and black screen 

[AtlasFrame] add light - 40x40 - [0]
[AtlasFrame] add camera - 40x40 - [0]
Warning: Low FPS: 1332.000000 tpf, 0.750751 fps 
Load shader: BuiltIn/Shader/Basic/VertexColor.xml
GLSL GL_VERTEX_SHADER shader failed to compile
0:1(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

**Comment by ducphamhong** [comment]
Hello Joilnen.
Do you use the SDL Backend?
And can you tell me what OS which you are using to run?

**Comment by Joilnen** [comment]
Yes SDL Backend and it's arch linux, only a embed intel GPU, but it is able to run irrlicht well.

**Comment by Joilnen** [comment]
Ok I found an workaround setting MESA_GL_VERSION_OVERRIDE=3.3
