### ISSUE TITLE
How to build on ios

### ISSUE THREAD

**Issue by zxm1985** [skylicht-lab/skylicht-engine#147]
Hello, I saw in the introduction of the engine that it supports Android and IOS system. At present, I have successfully compiled the client of MacOS version, but I don't know how to compile the client of IOS. Through cmake, I read all the documents I can see, but I didn't get the answer.Thank you.

**Comment by ducphamhong** [comment]
Hello, I am working on IOS, it isn't yet for Metal Driver.
The engine is already on OpenGLES but Apple dropped this feature. 
Instead, I am waiting for Google Angle but they have also not yet done it.
So I need more work on it.
Thanks,

**Comment by zxm1985** [comment]
First&nbsp;of&nbsp;all,&nbsp;thank&nbsp;you&nbsp;very&nbsp;much&nbsp;for&nbsp;replying&nbsp;to&nbsp;me.
Do&nbsp;you&nbsp;mean&nbsp;to&nbsp;launch&nbsp;the&nbsp;IOS&nbsp;version&nbsp;of&nbsp;skylicht&nbsp;project&nbsp;in&nbsp;the&nbsp;near&nbsp;future?
When&nbsp;I&nbsp;first&nbsp;learned&nbsp;game&nbsp;programming,&nbsp;I&nbsp;used&nbsp;Irrlicht.&nbsp;I&nbsp;like&nbsp;this&nbsp;engine&nbsp;very&nbsp;much.&nbsp;It&#39;s&nbsp;clean&nbsp;and&nbsp;free.
Let&nbsp;me&nbsp;introduce&nbsp;myself&nbsp;first.&nbsp;I&nbsp;am&nbsp;a&nbsp;programmer&nbsp;for&nbsp;visually&nbsp;impaired&nbsp;people.&nbsp;I&nbsp;will&nbsp;develop&nbsp;some&nbsp;cross&nbsp;platform&nbsp;blind&nbsp;games&nbsp;to&nbsp;enrich&nbsp;the&nbsp;amateur&nbsp;life&nbsp;of&nbsp;Chinese&nbsp;visually&nbsp;impaired&nbsp;people.
I&nbsp;don&#39;t&nbsp;have&nbsp;too&nbsp;high&nbsp;requirements&nbsp;for&nbsp;graphical&nbsp;interface.&nbsp;I&nbsp;have&nbsp;a&nbsp;greater&nbsp;demand&nbsp;for&nbsp;audio&nbsp;engine.&nbsp;I&nbsp;have&nbsp;introduced&nbsp;Fmod&nbsp;studio&nbsp;into&nbsp;your&nbsp;project.
And&nbsp;in&nbsp;the&nbsp;network&nbsp;layer,&nbsp;I&nbsp;connected&nbsp;websocketpp&nbsp;and&nbsp;protobuf,&nbsp;which&nbsp;also&nbsp;work&nbsp;well&nbsp;under&nbsp;wasm,
I&nbsp;look&nbsp;forward&nbsp;to&nbsp;the&nbsp;release&nbsp;of&nbsp;IOS&nbsp;project,&nbsp;even&nbsp;if&nbsp;it&nbsp;is&nbsp;not&nbsp;so&nbsp;perfect&nbsp;in&nbsp;display.
I&nbsp;use&nbsp;translation&nbsp;software&nbsp;to&nbsp;communicate&nbsp;with&nbsp;you.&nbsp;I&nbsp;am&nbsp;a&nbsp;Chinese&nbsp;programmer&nbsp;with&nbsp;visual&nbsp;impairment.
------&nbsp;原始邮件&nbsp;------
***@***.***&gt;;
发送时间:2022年5月11日(星期三)&nbsp;晚上6:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:Re:&nbsp;[skylicht-lab/skylicht-engine]&nbsp;How&nbsp;to&nbsp;build&nbsp;on&nbsp;ios&nbsp;(Issue&nbsp;#147)



 
Hello, I am working on IOS, it isn't yet for Metal Driver.
 The engine is already on OpenGLES but Apple dropped this feature.
 Instead, I am waiting for Google Angle but they have also not yet done it.
 So I need more work on it.
 Thanks,
 
&mdash;

**Comment by ducphamhong** [comment]
It already done for IOS now,
Thank you,
